In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
temp_df = pd.read_csv('VA_BR_Clinical_combo_matched_CMC_AMPAD_10082020.csv')

In [4]:
temp_df.head()

,Unnamed: 0,BB,SubNum,Batch1_Barcode,Batch1_Storage.Type,Batch1_Brain.Region,Batch1_UoM,Batch1_Size,Batch2_Barcode,Batch2_Storage.Type,...,CMC_ATACseq,CMC_ChIPSeq,CMC_microarray,CMC_proteomics,CMC_rnaSeq,CMC_SNP,CMC_WGS,AMPAD_msbb_individualID,Barcode_received,SNP_report:Genotyping_Sample_ID
0,1,475,64012,78073.0,Frozen Pulverized,BM-9/10/46,mg,50.0,140650.0,Frozen Pulverized,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,140650.0,NaN
1,2,543,89339,78095.0,Frozen Pulverized,BM-9/10/46,mg,50.0,113902.0,Frozen Pulverized,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113902.0,NaN
2,3,1265,84803,78103.0,Frozen Pulverized,BM-9/10/46,mg,50.0,16881.0,Frozen Pulverized,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMPAD_MSSM_0000084803,16881.0,NaN
3,4,1023,35594,78117.0,Frozen Pulverized,BM-9/10/46,mg,50.0,8296.0,Frozen Pulverized,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMPAD_MSSM_0000035594,8296.0,NaN
4,5,1017,18305,78126.0,Frozen Pulverized,BM-9/10/46,mg,50.0,8638.0,Frozen Pulverized,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AMPAD_MSSM_0000018305,8638.0,NaN

In [5]:
vcf = pd.read_csv('CMC_MSSM_NPSAD_genotyped_all.vcf.gz', skiprows=46, compression='gzip', sep='\t')

In [6]:
vcf.columns

Index(['#CHROM', 'POS', 'ID', 'REF', 'ALT', 'QUAL', 'FILTER', 'INFO', 'FORMAT',
       'MSSM_BP_1',
       ...
       'MSSM_81', 'MSSM_82', 'MSSM_84', 'MSSM_9', 'MSSM_91', 'MSSM_92',
       'MSSM_95', 'MSSM_96', 'MSSM_97', 'MSSM_98'],
      dtype='object', length=249)

In [7]:
temp_df = temp_df.loc[temp_df["SNP_report:Genotyping_Sample_ID"].dropna().index.tolist(), :]

In [8]:
temp_df.reset_index(drop=True)

,Unnamed: 0,BB,SubNum,Batch1_Barcode,Batch1_Storage.Type,Batch1_Brain.Region,Batch1_UoM,Batch1_Size,Batch2_Barcode,Batch2_Storage.Type,...,CMC_ATACseq,CMC_ChIPSeq,CMC_microarray,CMC_proteomics,CMC_rnaSeq,CMC_SNP,CMC_WGS,AMPAD_msbb_individualID,Barcode_received,SNP_report:Genotyping_Sample_ID
0,9,1431,7718,83166.0,Frozen Pulverized,BM-9/10/46,mg,50.0,208798.0,Frozen Pulverized,...,NaN,CMC_MSSM_379,NaN,NaN,CMC_MSSM_379,CMC_MSSM_379,CMC_MSSM_379,NaN,208798.0,MSSM_59
1,10,1245,22156,83169.0,Frozen Pulverized,BM-9/10/46,mg,50.0,208836.0,Frozen Pulverized,...,NaN,NaN,NaN,NaN,CMC_MSSM_381,CMC_MSSM_381,NaN,NaN,208836.0,MSSM_60
2,11,1158,79990,83172.0,Frozen Pulverized,BM-9/10/46,mg,50.0,115734.0,Frozen Pulverized,...,NaN,NaN,NaN,NaN,NaN,CMC_MSSM_374,NaN,NaN,115734.0,MSSM_54
3,16,181,78435,83937.0,Frozen Pulverized,BM-9/10/46,mg,50.0,214903.0,Frozen Pulverized,...,CMC_MSSM_366,CMC_MSSM_366,NaN,NaN,CMC_MSSM_366,CMC_MSSM_366,CMC_MSSM_366,NaN,214903.0,MSSM_47
4,31,1525,252323,104008.0,Frozen Pulverized,BM-9/10/46,mg,50.0,208721.0,Frozen Pulverized,...,NaN,NaN,NaN,NaN,CMC_MSSM_093,CMC_MSSM_093,NaN,AMPAD_MSSM_0000252323,208721.0,MSSM_160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,1204,1052,8231,194632.0,Frozen Pulverized,BM-9/10/46,mg,50.0,214711.0,Frozen Pulverized,...,CMC_MSSM_402,CMC_MSSM_402,NaN,NaN,CMC_MSSM_402,CMC_MSSM_402,CMC_MSSM_402,NaN,214711.0,MSSM_8
241,1208,739,70294,187685.0,Frozen Pulverized,BM-9/10/46,mg,50.0,NaN,NaN,...,CMC_MSSM_334,CMC_MSSM_334,NaN,NaN,CMC_MSSM_334,CMC_MSSM_334,NaN,NaN,NaN,MSSM_378
242,1240,1267,38814,NaN,NaN,NaN,NaN,NaN,111720.0,Frozen Pulverized,...,CMC_MSSM_260,CMC_MSSM_260,NaN,NaN,CMC_MSSM_260,CMC_MSSM_260,NaN,NaN,111720.0,MSSM_310
243,1243,24,90596,NaN,NaN,NaN,NaN,NaN,122876.0,Frozen Pulverized,...,NaN,NaN,NaN,NaN,CMC_MSSM_147,CMC_MSSM_147,CMC_MSSM_147,NaN,122876.0,MSSM_209
244,1245,25,77677,NaN,NaN,NaN,NaN,NaN,184611.0,Frozen Pulverized,...,NaN,NaN,NaN,NaN,CMC_MSSM_041,CMC_MSSM_041,CMC_MSSM_041,AMPAD_MSSM_0000077677,184611.0,MSSM_113

In [9]:
df_shan = pd.read_csv('/sc/arion/projects/psychAD/upload2synpase/final_NPSAD_snRNAseq_metrics_combo.csv')

In [10]:
df_shan.head(3)

,Unnamed: 0,SubID,Institution,BrainRegion,project,Rx,Set.number,HTO_ID,sample.ID,MULTIseq_number_of_cells,...,HTO_cDNA_Barcodes,HTO_cDNA_Set..,HTO_cDNA_Step.1.date.,HTO_cDNA_Set.number,HTO_cDNA_Set.Number,HTO_cDNA_Project,Doublet,Negative,flowcell,lane
0,1,M34302,MSSM,BM-9/10/46,NPSAD,NaN,1,NPSAD-20201013-A1-HTO,129185_BM-9/10/46,1798,...,TCTCGCGC,NaN,NaN,NaN,NaN,NaN,0.156592,0.267943,HLM3WDSXY,L003
1,2,H1873,HBCC,DLPFC,NPSAD,NaN,1,NPSAD-20201013-A1-HTO,1873_DLPFC,91,...,TCTCGCGC,NaN,NaN,NaN,NaN,NaN,0.156592,0.267943,HLM3WDSXY,L003
2,3,M34966,MSSM,BM-9/10/46,NPSAD,NaN,1,NPSAD-20201013-A1-HTO,194566_BM-9/10/46,1040,...,TCTCGCGC,NaN,NaN,NaN,NaN,NaN,0.156592,0.267943,HLM3WDSXY,L003

In [11]:
import re

In [12]:
def ret_samp(x):
    x = x[1:]
    
    return x

In [13]:
values = list(map(ret_samp, df_shan['SubID'].tolist()))
values = [ int(v) for v in values ]

In [15]:
temp_df.shape

(245, 109)

In [16]:
temp_df.loc[temp_df['SubNum'] ==36121, :]

,Unnamed: 0,BB,SubNum,Batch1_Barcode,Batch1_Storage.Type,Batch1_Brain.Region,Batch1_UoM,Batch1_Size,Batch2_Barcode,Batch2_Storage.Type,...,CMC_ATACseq,CMC_ChIPSeq,CMC_microarray,CMC_proteomics,CMC_rnaSeq,CMC_SNP,CMC_WGS,AMPAD_msbb_individualID,Barcode_received,SNP_report:Genotyping_Sample_ID
81,82,725,36121,116637.0,Frozen Pulverized,BM-9/10/46,mg,50.0,113941.0,Frozen Pulverized,...,NaN,NaN,NaN,NaN,CMC_MSSM_159,CMC_MSSM_159,NaN,AMPAD_MSSM_0000036121,113941.0,MSSM_22
928,929,725,36121,194337.0,Frozen Pulverized,BM-9/10/46,mg,50.0,113941.0,Frozen Pulverized,...,NaN,NaN,NaN,NaN,CMC_MSSM_159,CMC_MSSM_159,NaN,AMPAD_MSSM_0000036121,113941.0,MSSM_22

In [17]:
test_run = temp_df.loc[temp_df['SubNum'].isin(values) , ["SubNum", "SNP_report:Genotyping_Sample_ID"]]

In [18]:
test_run['SubNum'] = test_run['SubNum'].map(lambda x: 'M'+str(x))

In [19]:
samp_proc_vireo = df_shan.loc[df_shan['SubID'].isin(test_run['SubNum'].tolist()), 'cDNA_ID'].unique().tolist()

In [20]:
len(test_run['SubNum'])

141

In [21]:
len(test_run['SubNum'].unique())

140

In [22]:
test_run.reset_index(drop=True, inplace=True)

In [23]:
def ret_samp_names(y, df_info):
    #print(len(y), len(bc))
    if df_info.loc[df_info['SubID'] == y, 'cDNA_ID'].isnull().all():
        return ""
    else:
        return '-'.join(df_info.loc[df_info['SubID'] == y, 'cDNA_ID'].to_list()[0].split('-')[:3])[:-1]

In [24]:
len(test_run.values.tolist())

141

In [25]:
headers = ['#CHROM', 'POS', 'ID', 'REF', 'ALT', 'QUAL', 'FILTER', 'INFO', 'FORMAT'] + test_run["SNP_report:Genotyping_Sample_ID"].tolist()

In [26]:
headers = [h for h in headers if h in vcf.columns]

In [30]:
headers = [h for i, h in enumerate(headers) if h not in headers[:i]]

In [31]:
vcf_sub = vcf.loc[:, headers]

In [32]:
vcf_sub.head(3)

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,MSSM_59,...,MSSM_51,MSSM_186,MSSM_185,MSSM_122,MSSM_177,MSSM_66,MSSM_130,MSSM_8,MSSM_209,MSSM_113
0,chr1,903175,chr1:903175:C:A,C,A,.,PASS,.,GT:DS:HDS:GP,"1|0:0.963:0.962,0:0.038,0.962,0",...,"1|0:1:1,0:0,1,0","0|0:0.001:0,0.001:0.999,0.001,0","0|0:0.001:0.001,0:0.999,0.001,0","0|0:0.001:0,0.001:0.999,0.001,0","0|0:0.001:0.001,0:0.999,0.001,0","0|1:1:0,1:0,1,0","1|1:2:1,1:0,0,1","0|0:0.001:0,0.001:0.999,0.001,0","0|0:0:0,0:1,0,0","0|0:0.001:0,0.001:0.999,0.001,0"
1,chr1,911428,chr1:911428:C:T,C,T,.,PASS,.,GT:DS:HDS:GP,"0|0:0.001:0.001,0:0.999,0.001,0",...,"1|0:1:1,0:0,1,0","0|0:0:0,0:1,0,0","0|0:0:0,0:1,0,0","0|0:0:0,0:1,0,0","0|0:0:0,0:1,0,0","0|1:1:0,1:0,1,0","0|0:0:0,0:1,0,0","0|0:0:0,0:1,0,0","0|0:0:0,0:1,0,0","1|0:1:1,0:0,1,0"
2,chr1,918870,chr1:918870:A:G,A,G,.,PASS,.,GT:DS:HDS:GP,"0|0:0:0,0:1,0,0",...,"1|0:1:1,0:0,1,0","0|0:0:0,0:1,0,0","0|0:0.002:0.002,0:0.998,0.002,0","0|0:0:0,0:1,0,0","0|0:0:0,0:1,0,0","0|1:1:0,1:0,1,0","0|0:0:0,0:1,0,0","0|0:0:0,0:1,0,0","0|0:0:0,0:1,0,0","1|0:1:1,0:0,1,0"

In [33]:
test_run['SubNum']

0       M7718
1      M79990
2      M80700
3      M70412
4      M47207
        ...
136    M26756
137    M93392
138     M8231
139    M90596
140    M77677
Name: SubNum, Length: 141, dtype: object

In [34]:
temp_df_2 = test_run.copy()

In [35]:
temp_df_2 = temp_df_2[test_run["SNP_report:Genotyping_Sample_ID"].isin(vcf.columns.to_list()[9:])]

In [36]:
map_dict = temp_df_2.set_index('SNP_report:Genotyping_Sample_ID')['SubNum'].to_dict()

In [38]:
map_dict

{'MSSM_59': 'M7718',
 'MSSM_54': 'M79990',
 'MSSM_167': 'M80700',
 'MSSM_123': 'M70412',
 'MSSM_21': 'M47207',
 'MSSM_117': 'M43479',
 'MSSM_173': 'M84538',
 'MSSM_242': 'M77591',
 'MSSM_22': 'M36121',
 'MSSM_131': 'M40816',
 'MSSM_102': 'M11243',
 'MSSM_19': 'M29124',
 'MSSM_18': 'M76138',
 'MSSM_281': 'M94779',
 'MSSM_284': 'M51024',
 'MSSM_141': 'M14597',
 'MSSM_288': 'M46694',
 'MSSM_291': 'M71503',
 'MSSM_120': 'M40820',
 'MSSM_279': 'M15770',
 'MSSM_343': 'M7929',
 'MSSM_111': 'M12314',
 'MSSM_124': 'M6344',
 'MSSM_169': 'M11539',
 'MSSM_313': 'M24257',
 'MSSM_115': 'M99132',
 'MSSM_144': 'M88032',
 'MSSM_140': 'M40437',
 'MSSM_96': 'M48326',
 'MSSM_35': 'M75358',
 'MSSM_52': 'M78717',
 'MSSM_40': 'M84407',
 'MSSM_320': 'M67780',
 'MSSM_49': 'M5',
 'MSSM_97': 'M16169',
 'MSSM_84': 'M29736',
 'MSSM_237': 'M58301',
 'MSSM_BP_20': 'M25895',
 'MSSM_175': 'M61911',
 'MSSM_278': 'M10031',
 'MSSM_129': 'M12876',
 'MSSM_166': 'M73342',
 'MSSM_133': 'M14434',
 'MSSM_81': 'M36866',
 'MSSM_147': 'M66831',
 'MSSM_148': 'M32215',
 'MSSM_146': 'M75505',
 'MSSM_128': 'M7698',
 'MSSM_62': 'M79856',
 'MSSM_154': 'M95506',
 'MSSM_125': 'M33868',
 'MSSM_BP_15': 'M75093',
 'MSSM_4': 'M99364',
 'MSSM_204': 'M96533',
 'MSSM_157': 'M77549',
 'MSSM_298': 'M99182',
 'MSSM_34': 'M20356',
 'MSSM_6': 'M11589',
 'MSSM_45': 'M26012',
 'MSSM_29': 'M4310',
 'MSSM_67': 'M55555',
 'MSSM_176': 'M16717',
 'MSSM_328': 'M86494',
 'MSSM_91': 'M45480',
 'MSSM_9': 'M82391',
 'MSSM_2': 'M44145',
 'MSSM_377': 'M15257',
 'MSSM_10': 'M36915',
 'MSSM_26': 'M40274',
 'MSSM_82': 'M2850',
 'MSSM_121': 'M99877',
 'MSSM_63': 'M66858',
 'MSSM_95': 'M17230',
 'MSSM_68': 'M79033',
 'MSSM_105': 'M81548',
 'MSSM_80': 'M68642',
 'MSSM_28': 'M30150',
 'MSSM_293': 'M97856',
 'MSSM_231': 'M34836',
 'MSSM_37': 'M8926',
 'MSSM_56': 'M32931',
 'MSSM_321': 'M46660',
 'MSSM_170': 'M31079',
 'MSSM_155': 'M80488',
 'MSSM_168': 'M88010',
 'MSSM_134': 'M24508',
 'MSSM_119': 'M184',
 'MSSM_163': 'M89571',
 'MSSM_202': 'M1176',
 'MSSM_41': 'M56862',
 'MSSM_244': 'M8105',
 'MSSM_69': 'M94994',
 'MSSM_238': 'M7107',
 'MSSM_189': 'M48223',
 'MSSM_152': 'M5101',
 'MSSM_BP_21': 'M35723',
 'MSSM_348': 'M48037',
 'MSSM_36': 'M16485',
 'MSSM_BP_4': 'M45880',
 'MSSM_304': 'M23398',
 'MSSM_229': 'M26279',
 'MSSM_296': 'M96154',
 'MSSM_112': 'M79245',
 'MSSM_290': 'M81065',
 'MSSM_289': 'M62918',
 'MSSM_44': 'M71734',
 'MSSM_BP_5': 'M84126',
 'MSSM_230': 'M70693',
 'MSSM_13': 'M54529',
 'MSSM_109': 'M87879',
 'MSSM_240': 'M36047',
 'MSSM_251': 'M42635',
 'MSSM_236': 'M65046',
 'MSSM_101': 'M37112',
 'MSSM_280': 'M84511',
 'MSSM_100': 'M62951',
 'MSSM_250': 'M55613',
 'MSSM_197': 'M38932',
 'MSSM_300': 'M55245',
 'MSSM_311': 'M53706',
 'MSSM_5': 'M67720',
 'MSSM_BP_9': 'M69057',
 'MSSM_BP_11': 'M54382',
 'MSSM_BP_18': 'M73555',
 'MSSM_287': 'M99907',
 'MSSM_BP_16': 'M65019',
 'MSSM_BP_13': 'M5548',
 'MSSM_210': 'M6362',
 'MSSM_BP_24': 'M9699',
 'MSSM_51': 'M63499',
 'MSSM_186': 'M12249',
 'MSSM_185': 'M10886',
 'MSSM_122': 'M26992',
 'MSSM_177': 'M9161',
 'MSSM_66': 'M26756',
 'MSSM_130': 'M93392',
 'MSSM_8': 'M8231',
 'MSSM_209': 'M90596',
 'MSSM_113': 'M77677'}

In [39]:
vcf_sub.rename(columns=map_dict, inplace=True)

In [40]:
vcf_sub.head(3)

,#CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,M7718,...,M63499,M12249,M10886,M26992,M9161,M26756,M93392,M8231,M90596,M77677
0,chr1,903175,chr1:903175:C:A,C,A,.,PASS,.,GT:DS:HDS:GP,"1|0:0.963:0.962,0:0.038,0.962,0",...,"1|0:1:1,0:0,1,0","0|0:0.001:0,0.001:0.999,0.001,0","0|0:0.001:0.001,0:0.999,0.001,0","0|0:0.001:0,0.001:0.999,0.001,0","0|0:0.001:0.001,0:0.999,0.001,0","0|1:1:0,1:0,1,0","1|1:2:1,1:0,0,1","0|0:0.001:0,0.001:0.999,0.001,0","0|0:0:0,0:1,0,0","0|0:0.001:0,0.001:0.999,0.001,0"
1,chr1,911428,chr1:911428:C:T,C,T,.,PASS,.,GT:DS:HDS:GP,"0|0:0.001:0.001,0:0.999,0.001,0",...,"1|0:1:1,0:0,1,0","0|0:0:0,0:1,0,0","0|0:0:0,0:1,0,0","0|0:0:0,0:1,0,0","0|0:0:0,0:1,0,0","0|1:1:0,1:0,1,0","0|0:0:0,0:1,0,0","0|0:0:0,0:1,0,0","0|0:0:0,0:1,0,0","1|0:1:1,0:0,1,0"
2,chr1,918870,chr1:918870:A:G,A,G,.,PASS,.,GT:DS:HDS:GP,"0|0:0:0,0:1,0,0",...,"1|0:1:1,0:0,1,0","0|0:0:0,0:1,0,0","0|0:0.002:0.002,0:0.998,0.002,0","0|0:0:0,0:1,0,0","0|0:0:0,0:1,0,0","0|1:1:0,1:0,1,0","0|0:0:0,0:1,0,0","0|0:0:0,0:1,0,0","0|0:0:0,0:1,0,0","1|0:1:1,0:0,1,0"

In [41]:
vcf_sub.to_csv('Sub_vcf.vcf', sep='\t', index=False)

In [42]:
test_run['Samp_ID'] = test_run['SubNum'].apply(ret_samp_names, args=(df_shan, ))

In [43]:
test_run.drop_duplicates(inplace=True, ignore_index=True)

In [44]:
test_run

     SubNum SNP_report:Genotyping_Sample_ID           Samp_ID
0     M7718                         MSSM_59  NPSAD-20210303-A
1    M79990                         MSSM_54  NPSAD-20201221-A
2    M80700                        MSSM_167
3    M70412                        MSSM_123  NPSAD-20210219-C
4    M47207                         MSSM_21
..      ...                             ...               ...
135  M26756                         MSSM_66  NPSAD-20210216-A
136  M93392                        MSSM_130  NPSAD-20210113-C
137   M8231                          MSSM_8  NPSAD-20210211-C
138  M90596                        MSSM_209
139  M77677                        MSSM_113  NPSAD-20210114-A

[140 rows x 3 columns]

In [45]:
test_run.to_csv('Hash_map_gtID_SubID.csv', index=False)

In [45]:
a = pd.read_csv('Hash_map_gtID_SubID.csv', names=['SubNum', 'VCF_ID', 'Sample_ID'], skiprows=1)

In [53]:
from collections import Counter

In [54]:
Counter(a['Sample_ID'])

Counter({'NPSAD-20210303-A': 1,
         'NPSAD-20201221-A': 1,
         nan: 43,
         'NPSAD-20210219-C': 1,
         'NPSAD-20201103-A': 1,
         'NPSAD-20201216-C': 1,
         'NPSAD-20201112-A': 3,
         'NPSAD-20210312-A': 2,
         'NPSAD-20201104-C': 2,
         'NPSAD-20201028-C': 1,
         'NPSAD-20210318-A': 1,
         'NPSAD-20201027-C': 1,
         'NPSAD-20201202-C': 1,
         'NPSAD-20201221-C': 1,
         'NPSAD-20201019-C': 2,
         'NPSAD-20201124-C': 1,
         'NPSAD-20201215-C': 4,
         'NPSAD-20201105-C': 2,
         'NPSAD-20201029-A': 1,
         'NPSAD-20201106-C': 1,
         'NPSAD-20201113-C': 3,
         'NPSAD-20201214-C': 2,
         'NPSAD-20210305-A': 1,
         'NPSAD-20210217-C': 3,
         'NPSAD-20201030-A': 2,
         'NPSAD-20210304-A': 1,
         'NPSAD-20201120-A': 1,
         'NPSAD-20210126-A': 2,
         'NPSAD-20201118-A': 2,
         'NPSAD-20210204-A': 2,
         'NPSAD-20210121-A': 1,
         'NPSAD-20210113-A': 1,
         'NPSAD-20210126-C': 1,
         'NPSAD-20201211-A': 1,
         'NPSAD-20210217-A': 1,
         'NPSAD-20210119-A': 1,
         'NPSAD-20210205-A': 2,
         'NPSAD-20201202-A': 1,
         'NPSAD-20201023-A': 2,
         'NPSAD-20201030-C': 5,
         'NPSAD-20201208-C': 1,
         'NPSAD-20201117-C': 1,
         'NPSAD-20210216-C': 1,
         'NPSAD-20210121-C': 2,
         'NPSAD-20201020-A': 1,
         'NPSAD-20201021-A': 1,
         'NPSAD-20201218-C': 1,
         'NPSAD-20201111-A': 1,
         'NPSAD-20210114-C': 1,
         'NPSAD-20201124-A': 1,
         'NPSAD-20201015-C': 1,
         'NPSAD-20201125-A': 1,
         'NPSAD-20210211-A': 1,
         'NPSAD-20201123-C': 2,
         'NPSAD-20201125-C': 1,
         'NPSAD-20210119-C': 1,
         'NPSAD-20210223-C': 2,
         'NPSAD-20201120-C': 1,
         'NPSAD-20201105-A': 1,
         'NPSAD-20201110-C': 1,
         'NPSAD-20210212-C': 1,
         'NPSAD-20201027-A': 1,
         'NPSAD-20210129-C': 1,
         'NPSAD-20201029-C': 1,
         'NPSAD-20210216-A': 2,
         'NPSAD-20201204-C': 1,
         'NPSAD-20201106-A': 1,
         'NPSAD-20210113-C': 1,
         'NPSAD-20210211-C': 1,
         'NPSAD-20210114-A': 1})

In [60]:
','.join(a.loc[a['Sample_ID'] == 'NPSAD-20201027-A2-cDNA'[:-6], 'SubNum'].to_list())

'M37112'

In [46]:
with open('samples_for_vireo.txt', 'w') as f:
    for item in samp_proc_vireo:
        f.write("%s\n" % item)